### ISSUE TITLE
Missing frfuel.net.dll

### ISSUE THREAD

**Issue by MasterManwah** [RiderSx/FRFuel#32]
Hello, there seems to be a file missing "frfuel.net.dll". 
As stated in the __resource.lua below:
`resource_manifest_version '44febabe-d386-4d18-afbe-5e627f4af937'
files { 
    "config.ini",
    "Newtonsoft.Json.dll",
    "GasStations.json"
}
client_script "frfuel.net.dll"`

I am unable to find "frfuel.net.dll". 
Which causes an error upon trying to join the server.

**Comment by thers** [comment]
Try reinstalling the resource, it appears something has deleted that particular file. Follow installation instructions precisely! If issue will remain please open new issue here, thanks!
