### ISSUE TITLE
fuel not syncing when players inside vehicle

### ISSUE THREAD

**Issue by manups4e** [RiderSx/FRFuel#33]
Sometimes it happens that when i go to refuel vehicle to gas stations and other players are inside my vehicle while i refuel it.. when i get back into vehicle, fuel is reset to the players state and not the refueled state..
it's like that it doesn't refuel when other players are inside vehicle during refuel

**Comment by manups4e** [comment]
seems like the version i'm using is different as yours wants the ped to be inside vehicle to refuel.. sorry my bad

**Comment by Peekofwar** [comment]
> seems like the version i'm using is different as yours wants the ped to be inside vehicle to refuel.. sorry my bad

What version is that? I really want a refueling resource that requires you to exit the vehicle...

**Comment by manups4e** [comment]
too late i made my own already
